version: '3.7'

services:
  subletdetector-postgres:
    image: postgres:12.2-alpine
    ports:
      - 127.0.0.1:${PORTS__POSTGRES:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES__USER:-iteamadmin}
      - POSTGRES_PASSWORD=${POSTGRES__PASS:-adminadmin1337}
      - POSTGRES_DB=${POSTGRES__DB:-subletdetector}
      - POSTGRES_INITDB_ARGS=--encoding=utf8
    networks:
      subletdetector:
        aliases:
          - postgres
          - pg

networks:
  subletdetector:
