version: '3.7'

services:
  subletdetector-postgres:
    image: postgres:12.2-alpine
    ports:
      - 127.0.0.1:${PORTS__POSTGRES:-5442}:5432
    environment:
      - POSTGRES_USER=${POSTGRES__USER:-iteamadmin}
      - POSTGRES_PASSWORD=${POSTGRES__PASS:-adminadmin1337}
      - POSTGRES_DB=${POSTGRES__DB:-subletdetector}
      - POSTGRES_INITDB_ARGS=--encoding=utf8
    networks:
      subletdetector:
        aliases:
          - postgres
          - pg
  slussen:
    image: docker.pkg.github.com/allmannyttan/slussen/slussen:latest
    ports:
      - 4000:4000
    networks:
      - slussen
    environment:
      - 'PORT=${PORT:-4000}'
      - 'FAST_API__BASE_URL=${FASTAPIBASEURL:-http://www.fastapi.se/backendprop/v1/api/}'
      - 'FAST_API__ACCESS_TOKEN=${FASTAPIACCESSTOKEN:-12345}'
      - 'FAST_API__USER=${FASTAPIUSER:-demouser}'
      - 'FAST_API__PASSWORD=${FASTAPIPASSWORD:-demopassword}'
      - 'DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgrespassword@postgres:5432/api-db}'
      - 'POSTGRES__HOST=${POSTGRESHOST:-postgres}'
  postgres:
    image: postgres:12.2-alpine
    networks:
      - slussen
    environment:
      TZ: Europe/Stockholm
      POSTGRES_DB: api-db
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  subletdetector:
  slussen:

volumes:
  db-data:
    driver: local
